site_name: AFTpy

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy

nav:
  - AFTpy: index.md
  - AFTMap: aftmap.md
  - GetAFTData: getaftdata.md
